### ISSUE TITLE
Numeric value out of range: 'tour_id'

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-mobitech#10]
## Problem / motivation

`Numeric value out of range: 1264 Out of range value for column 'tour_id' at row 1`

The value in question is '70319703201400'

## Suggested resolution

Expand columns which are fitted in size based on earlier data sets to have plenty of room. Rationale discussed in #TromsFylkestrafikk/ragnarok-skyttel#16.

## DoD

- [x] Columns with specified/narrowed column space should be widened to its full potential. e.g. char(14) –> char()
- [x] Numeric columns should use bigInteger() for ID-alike values

**Comment by tft-kyrre** [comment]
To help with testing, it would be beneficial to know the chunk date where this problem occurs.

**Comment by tfk-kaare** [comment]
Have a look at prod. ragnarok.tftservice.no :-)

**Comment by tfk-kaare** [comment]
In progress?

**Comment by tft-kyrre** [comment]
Note to self: Seems like import has failed more or less constantly since 2024-06-27. Succeeded yesterday, but failed the day before (2024-08-14).
