### ISSUE TITLE
Contact Mobitech and request for different access of raw data

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-mobitech#7]
Today, accessing a day's amount of data includes downloading thousands of individual files from a cloud service. This is very time consuming.

## Suggested resolution

Contact Mobitech and request for accessing chunks of data in a more compact way.

**Comment by tft-kyrre** [comment]
Email sent to Tom Langvik at Mobitech.

**Comment by tfk-kaare** [comment]
Summary of meeting:

Mobitech will fish for experience of this service from other parties, and do an internal evaluation and voting regarding how to solve it and the amount of work doing so. They will contact us with the results of this at earliest next week.

We made it clear that this is an annoyance more than a critical error.

**Comment by tfk-kaare** [comment]
about time to send a new reqest for update?

**Comment by tft-kyrre** [comment]
I suggest sending an email Monday morning. Tom usually responds quickly.

**Comment by tft-kyrre** [comment]
Results collected from Mobitech's clients:

- Client A: 6000 transactions per minute
- Client B: 2250 transactions per minute
- Client C: 265 transactions per minute
- Client D (TFK): 100 transactions per minute

**Comment by tft-kyrre** [comment]
Sent 6 ZIP-files (chunk 2024-06-02) to Mobitech for transfer speed testing.
They made the files available on Azure storage as:
- test/101010/101010_transactions.zip
- test/101010/101010_statistics.zip
- test/101677/101677_transactions.zip
- test/101677/101677_statistics.zip
- test/101678/101678_transactions.zip
- test/101678/101678_statistics.zip

**Comment by tft-kyrre** [comment]
Testing download (no unzipping) of the 6 ZIP-files using modified source code: Completed in < 5 seconds!
Normal download time for this chunk (3006 individual files) was ~16 minutes, so from this we can conclude that using compressed files makes a HUGE improvement.

Asked Tom if they could do this as a permanent solution.

**Comment by tft-kyrre** [comment]
Tom at Mobitech informed me that they are indeed working on a prototype for zipping transaction files, which is good news.

**Comment by tfk-kaare** [comment]
Good news everyone!

**Comment by tft-kyrre** [comment]
The meeting with Mobitech yesterday included a demo where they had produced zipped files ready for full-scale testing.
All files (transactions and statistics) for a single day are now compressed into a single archive and stored in a dedicated folder on Azure.
They won't produce ZIP files with retroactive effect, so we must support both download methods at our end.

A new issue will be created for implementation of the new ZIP download method.
